INSERT INTO notice_source
    (code, name, url, created)
VALUES
    ('Do','Gnome Do','http://do.davebsd.com/wiki/index.php?title=Microblog_Plugin', now()),
    ('Facebook','Facebook','http://apps.facebook.com/identica/', now()),
    ('Gwibber','Gwibber','http://launchpad.net/gwibber', now()),
    ('HelloTxt','HelloTxt','http://hellotxt.com/', now()),
    ('IdentiFox','IdentiFox','http://www.bitbucket.org/uncryptic/identifox/', now()),
    ('LaTwit','LaTwit','http://latwit.mac65.com/', now()),
    ('Nambu','Nambu','http://www.nambu.com/', now()),
    ('Pikchur','Pikchur','http://www.pikchur.com/', now()),
    ('Ping.fm','Ping.fm','http://ping.fm/', now()),
    ('Twidge','Twidge','http://software.complete.org/twidge', now()),
    ('Updating.Me','Updating.Me','http://updating.me/', now()),
    ('betwittered','BeTwittered','http://www.32hours.com/betwitteredinfo/', now()),
    ('bti','bti','http://gregkh.github.com/bti/', now()),
    ('deskbar','Deskbar-Applet','http://www.gnome.org/projects/deskbar-applet/', now()),
    ('identicatools','Laconica Tools','http://bitbucketlabs.net/laconica-tools/', now()),
    ('identichat','identichat','http://identichat.prosody.im/', now()),
    ('identitwitch','IdentiTwitch','http://richfish.org/identitwitch/', now()),
    ('mbpidgin','mbpidgin','http://code.google.com/p/microblog-purple/', now()),
    ('moconica','Moconica','http://moconica.com/', now()),
    ('pocketwit','PockeTwit','http://code.google.com/p/pocketwit/', now()),
    ('posty','Posty','http://spreadingfunkyness.com/posty/', now()),
    ('royalewithcheese','Royale With Cheese','http://p.hellyeah.org/', now()),
    ('rssdent','rssdent','http://github.com/zcopley/rssdent/tree/master', now()),
    ('rygh.no','rygh.no','http://rygh.no/', now()),
    ('ryghsms','ryghsms','http://sms.rygh.no/', now()),
    ('smob','SMOB','http://smob.sioc-project.org/', now()),
    ('spaz','Spaz','http://funkatron.com/spaz', now()),
    ('tarpipe','tarpipe','http://tarpipe.com/', now()),
    ('tjunar','Tjunar','http://nederflash.nl/boek/titels/tjunar-air', now()),
    ('tr.im','tr.im','http://tr.im/', now()),
    ('tweenky','Tweenky','http://beta.tweenky.com/', now()),
    ('twhirl','Twhirl','http://www.twhirl.org/', now()),
    ('twibble','twibble','http://www.twibble.de/', now()),
    ('twidge','Twidge','http://software.complete.org/twidge', now()),
    ('twidroid','twidroid','http://www.twidroid.com/', now()),
    ('twittelator','Twittelator','http://www.stone.com/iPhone/Twittelator/', now()),
    ('twitterfeed','twitterfeed','http://twitterfeed.com/', now()),
    ('twitterphoto','TwitterPhoto','http://richfish.org/twitterphoto/', now()),
    ('twitterpm','Net::Twitter','http://search.cpan.org/dist/Net-Twitter/', now()),
    ('twittertools','Twitter Tools','http://wordpress.org/extend/plugins/twitter-tools/', now()),
    ('twitux','Twitux','http://live.gnome.org/DanielMorales/Twitux', now()),
    ('twitvim','TwitVim','http://vim.sourceforge.net/scripts/script.php?script_id=2204', now()),
    ('urfastr','urfastr','http://urfastr.net/', now());
