INSERT INTO notice_source
    (code, name, url, created)
VALUES
    ('adium', 'Adium', 'http://www.adiumx.com/', now()),
    ('Afficheur', 'Afficheur', 'http://afficheur.sourceforge.jp/', now()),
    ('AgentSolo.com','AgentSolo.com','http://www.agentsolo.com/', now()),
    ('anyio', 'Any.IO', 'http://any.io/', now()),
    ('betwittered','BeTwittered','http://www.32hours.com/betwitteredinfo/', now()),
    ('bti','bti','http://gregkh.github.com/bti/', now()),
    ('choqok', 'Choqok', 'http://choqok.gnufolks.org/', now()),
    ('cliqset', 'Cliqset', 'http://www.cliqset.com/', now()),
    ('DarterosStatus', 'Darteros Status', 'http://www.darteros.com/doc/Darteros_Status', now()),
    ('deskbar','Deskbar-Applet','http://www.gnome.org/projects/deskbar-applet/', now()),
    ('Do','Gnome Do','http://do.davebsd.com/wiki/index.php?title=Microblog_Plugin', now()),
    ('drupal','Drupal','http://drupal.org/', now()),
    ('eventbox','EventBox','http://thecosmicmachine.com/eventbox/', now()),
    ('identica-mode','Emacs Identica-mode','http://nongnu.org/identica-mode/', now()),
    ('Facebook','Facebook','http://apps.facebook.com/identica/', now()),
    ('feed2omb','feed2omb','http://projects.ciarang.com/p/feed2omb/', now()),
    ('get2gnow', 'get2gnow', 'http://uberchicgeekchick.com/?projects=get2gnow', now()),
    ('gNewBook', 'gNewBook', 'http://www.gnewbook.org/', now()),
    ('gravity', 'Gravity', 'http://mobileways.de/gravity', now()),
    ('Gwibber','Gwibber','http://launchpad.net/gwibber', now()),
    ('HelloTxt','HelloTxt','http://hellotxt.com/', now()),
    ('identicatools','Laconica Tools','http://bitbucketlabs.net/laconica-tools/', now()),
    ('identichat','identichat','http://identichat.prosody.im/', now()),
    ('IdentiCurse','IdentiCurse','http://identicurse.net/', now()),
    ('IdentiFox','IdentiFox','http://www.bitbucket.org/uncryptic/identifox/', now()),
    ('identitwitch','IdentiTwitch','http://richfish.org/identitwitch/', now()),
    ('Jiminy','Jiminy','http://code.google.com/p/jiminy/', now()),
    ('LaTwit','LaTwit','http://latwit.mac65.com/', now()),
    ('LiveTweeter', 'LiveTweeter', 'http://addons.songbirdnest.com/addon/1204', now()),
    ('livetweeter', 'livetweeter', 'http://addons.songbirdnest.com/addon/1204', now()),
    ('maisha', 'Maisha', 'http://maisha.grango.org/', now()),
    ('mbpidgin','mbpidgin','http://code.google.com/p/microblog-purple/', now()),
    ('Mobidentica', 'Mobidentica', 'http://www.substanceofcode.com/software/mobidentica/', now()),
    ('moconica','Moconica','http://moconica.com/', now()),
    ('mustard', 'mustard', 'http://mustard.macno.org', now()),
    ('nambu','Nambu','http://www.nambu.com/', now()),
    ('peoplebrowsr', 'PeopleBrowsr', 'http://www.peoplebrowsr.com/', now()),
    ('Pikchur','Pikchur','http://www.pikchur.com/', now()),
    ('Ping.fm','Ping.fm','http://ping.fm/', now()),
    ('pingvine','PingVine','http://pingvine.com/', now()),
    ('pocketwit','PockeTwit','http://code.google.com/p/pocketwit/', now()),
    ('posty','Posty','http://spreadingfunkyness.com/posty/', now()),
    ('qtwitter','qTwitter','http://qtwitter.ayoy.net/', now()),
    ('qwit', 'Qwit', 'http://code.google.com/p/qwit/', now()),
    ('royalewithcheese','Royale With Cheese','http://p.hellyeah.org/', now()),
    ('rssdent','rssdent','http://github.com/zcopley/rssdent/tree/master', now()),
    ('rygh.no','rygh.no','http://rygh.no/', now()),
    ('ryghsms','ryghsms','http://sms.rygh.no/', now()),
    ('smob','SMOB','http://smob.sioc-project.org/', now()),
    ('socialoomphBfD4pMqz31', 'SocialOomph', 'http://www.socialoomph.com/', now()),
    ('spaz','Spaz','http://funkatron.com/spaz', now()),
    ('StatusNet Desktop', 'StatusNet Desktop', 'http://status.net/desktop', now()),
    ('StatusNet Mobile', 'StatusNet Mobile', 'http://status.net/mobile', now()),
    ('StatusNet iPhone', 'iPhone', 'http://status.net/iphone', now()),
    ('StatusNet Android', 'Android', 'http://status.net/android', now()),
    ('StatusNet Blackberry', 'Blackberry', 'http://status.net/blackberry', now()),
    ('tarpipe','tarpipe','http://tarpipe.com/', now()),
    ('tjunar','Tjunar','http://nederflash.nl/boek/titels/tjunar-air', now()),
    ('tr.im','tr.im','http://tr.im/', now()),
    ('triklepost', 'Tricklepost', 'http://github.com/zcopley/tricklepost/tree/master', now()),
    ('tweenky','Tweenky','http://beta.tweenky.com/', now()),
    ('TweetDeck', 'TweetDeck', 'http://www.tweetdeck.com/', now()),
    ('twhirl','Twhirl','http://www.twhirl.org/', now()),
    ('twibble','twibble','http://www.twibble.de/', now()),
    ('Twidge','Twidge','http://software.complete.org/twidge', now()),
    ('twidge','Twidge','http://software.complete.org/twidge', now()),
    ('twidroid','twidroid','http://www.twidroid.com/', now()),
    ('twittelator','Twittelator','http://www.stone.com/iPhone/Twittelator/', now()),
    ('twitter','Twitter','http://twitter.com/', now()),
    ('twitterfeed','twitterfeed','http://twitterfeed.com/', now()),
    ('twitterphoto','TwitterPhoto','http://richfish.org/twitterphoto/', now()),
    ('twitterpm','Net::Twitter','http://search.cpan.org/dist/Net-Twitter/', now()),
    ('twittertools','Twitter Tools','http://wordpress.org/extend/plugins/twitter-tools/', now()),
    ('twitux','Twitux','http://live.gnome.org/DanielMorales/Twitux', now()),
    ('twitvim','TwitVim','http://vim.sourceforge.net/scripts/script.php?script_id=2204', now()),
    ('Updating.Me','Updating.Me','http://updating.me/', now()),
    ('urfastr','urfastr','http://urfastr.net/', now()),
    ('yatca','Yatca','http://www.yatca.com/', now()),
    ('rss.me', 'rss.me', 'http://rss.me/', now());
